# SPDX-License-Identifier: GPL-2.0
#============================================================================
# Name        : Edac_app.c
# Author      : gabriele.paoloni@intel.com
# Version     :
# Copyright   : Copyright (c) 2020, Intel Corporation.
# Description : Hello World in C, Ansi-style
#============================================================================

edac_app: edac_app.c
	gcc -o edac_app edac_app.c -lgpiod
